data_root: data/VOCdevkit
train_list: data/cache/train.txt
test_list: data/cache/test07.txt

img_size: 448
S: 7
B: 2
C: 20

batch_size: 64
epochs: 135
lr: 1e-3
momentum: 0.9
weight_decay: 0.0005
warmup_epochs: 2
lr_steps: [60, 90, 120] # step decay
lr_gamma: 0.1

lambda_coord: 5.0
lambda_noobj: 0.5
